name: CI (build + DB schema check)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: C:\vcpkg
      BUILD_DIR: build
      BUILD_TYPE: Release
      EXE_DIR: build\Release
      DB_PATH: ${{ github.workspace }}\data\mission-metadata.db

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sqlite CLI
        shell: pwsh
        run: |
          choco install sqlite -y

      - name: Install vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg $env:VCPKG_ROOT
          & $env:VCPKG_ROOT\bootstrap-vcpkg.bat

      - name: Cache vcpkg artifacts
        uses: actions/cache@v4
        with:
          path: |
            C:\vcpkg\installed\
            C:\vcpkg\downloads\
          key: vcpkg-${{ runner.os }}-x64-windows-${{ hashFiles('vcpkg.json') }}

      - name: Configure (CMake + vcpkg toolchain, Visual Studio)
        shell: pwsh
        run: |
          & "C:\Program Files\CMake\bin\cmake.exe" -S . -B $env:BUILD_DIR -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows `
            -DVCPKG_MANIFEST_MODE=ON

      - name: Build
        shell: pwsh
        run: |
          & "C:\Program Files\CMake\bin\cmake.exe" --build $env:BUILD_DIR --config $env:BUILD_TYPE

      - name: Ensure schema next to mdm (belt & suspenders)
        shell: pwsh
        run: |
          Copy-Item -Force src/core/metadata/schema.sql "$env:EXE_DIR\schema.sql"

      - name: Initialize DB (mdm --init)
        shell: pwsh
        working-directory: ${{ env.EXE_DIR }}
        run: |
          New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE\data" | Out-Null
          $env:MDM_DB_PATH = "${{ env.DB_PATH }}"
          .\mdm.exe --init

      - name: Verify DB tables
        shell: pwsh
        run: |
          if (-not (Test-Path "${{ env.DB_PATH }}")) { throw "DB not created: $env:DB_PATH" }
          $tables = & sqlite3 "${{ env.DB_PATH }}" ".tables"
          Write-Host "Tables:`n$tables"
          if ($tables -notmatch '\bobjects\b' -or $tables -notmatch '\bobject_history\b') {
            throw "Required tables missing (objects/object_history)."
          }
